name       : python-sphinxcontrib-serializinghtml
version    : 1.1.4
release    : 2
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-serializinghtml/archive/1.1.4.tar.gz : 0523cd005e88b9c8b60ac03ead8236724d579cd141000d191f42133b849ffa29
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for outputting serialized HTML files
description: |
    sphinxcontrib-serializinghtml is a sphinx extension which outputs "serialized" HTML files (json and pickle).
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
