name       : python-sphinxcontrib-serializinghtml
version    : 1.1.5
release    : 4
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-serializinghtml/archive/refs/tags/1.1.5.tar.gz : 787a346f2593bf324c2e8096f23d3d5d0727cb990dc697222acff3daaa42ba1e
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for outputting serialized HTML files
description: |
    sphinxcontrib-serializinghtml is a sphinx extension which outputs "serialized" HTML files (json and pickle).
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
