name       : python-sphinxcontrib-serializinghtml
version    : 1.1.5
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/s/sphinxcontrib-serializinghtml/sphinxcontrib-serializinghtml-1.1.5.tar.gz : aa5f6de5dfdf809ef505c4895e51ef5c9eac17d0f287933eb49ec495280b6952
homepage   : https://www.sphinx-doc.org/en/master/
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for outputting serialized HTML files
description: |
    sphinxcontrib-serializinghtml is a sphinx extension which outputs "serialized" HTML files (json and pickle).
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
