name       : python-sphinxcontrib-serializinghtml
version    : 1.1.2
release    : 1
source     :
    - https://github.com/sphinx-doc/sphinxcontrib-serializinghtml/archive/1.1.2.tar.gz : 25459ddcf20713488780d956c5b17c60cc964b31cfebfd861ca796f01fb19698
license    : BSD-2-Clause
component  : programming.python
summary    : Sphinx extension for outputting serialized HTML files
description: |
    sphinxcontrib-serializinghtml is a sphinx extension which outputs "serialized" HTML files (json and pickle).
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
